#!/usr/bin/env python3
"""Dump the world's sales substrate so tasks can be authored against real rows.

    python3 scripts/probe-world.py [--url http://localhost:8971] [--out world-facts.md]

Task authoring needs ground truth: exact ids, exact values, exact counts. Writing
checks from memory is how a benchmark ends up asserting things the world never
contained. This prints schema + the rows that decisions hinge on.
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parents[1]

# The tables a sales task can plausibly turn on, grouped the way a seller thinks.
GROUPS = {
    "pipeline": ["accounts", "contacts", "opportunities", "sales_opportunities", "sales_leads"],
    "quoting": ["sales_quotes", "sales_quote_lines", "product_catalog_items"],
    "forecast": ["rep_quotas", "forecast_submissions"],
    "outbound": ["outreach_sequences", "outreach_sequence_steps", "outreach_enrollments",
                 "email_threads", "email_messages", "campaign_touches"],
    "customer": ["account_health", "account_usage", "service_cases", "cases", "support_tickets"],
    "contracts": ["signature_envelopes"],
    "people": ["employees"],
    "hygiene": ["lead_merge_log", "data_quality_rules"],
}


def rpc(url: str, sql: str, params=None, db="state"):
    req = urllib.request.Request(
        f"{url}/verifier/query",
        data=json.dumps({"sql": sql, "params": params or [], "db": db}).encode(),
        headers={"content-type": "application/json", "X-Verifier-Token": "harbor-verifier-token"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read())["rows"]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default="http://localhost:8971")
    ap.add_argument("--db", default=None, help="read a local seed.db instead of a running server")
    ap.add_argument("--out", default=str(HERE / "world-facts.md"))
    ap.add_argument("--rows", type=int, default=12)
    args = ap.parse_args()

    if args.db:
        conn = sqlite3.connect(args.db)
        conn.row_factory = sqlite3.Row
        run = lambda sql, params=None: [dict(r) for r in conn.execute(sql, params or [])]
    else:
        run = lambda sql, params=None: rpc(args.url, sql, params)

    out = ["# World facts — sales substrate", "",
           "Generated by `scripts/probe-world.py`. Author task checks against these",
           "exact ids and values; never from memory.", ""]

    for group, tables in GROUPS.items():
        out.append(f"## {group}")
        out.append("")
        for t in tables:
            try:
                n = run(f"SELECT COUNT(*) AS n FROM {t}")[0]["n"]
            except Exception:
                continue
            rows = run(f"SELECT * FROM {t} LIMIT {args.rows}")
            cols = list(rows[0].keys()) if rows else []
            out.append(f"### `{t}` — {n} rows")
            out.append("")
            out.append(f"columns: `{', '.join(cols)}`")
            out.append("")
            if rows:
                out.append("```json")
                for r in rows:
                    out.append(json.dumps(r, default=str))
                if n > len(rows):
                    out.append(f"... {n - len(rows)} more")
                out.append("```")
            out.append("")

    Path(args.out).write_text("\n".join(out))
    print(f"wrote {args.out} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
