#!/usr/bin/env python3
"""Add the CRM entities that production CRMs model and this world did not.

    python3 scripts/build-entity-coverage-spec.py
    python3 scripts/densify-vendor-tools.py

`docs/SCHEMA-COVERAGE.md` measures the world against 3,233 tables extracted from 27
production CRM/ERP codebases. It sat at 23 of 43 core entities (53%) — an entity
counts as core when at least three independent product families model it.

This closes the domain half of that gap. Each table here is an entity several
unrelated CRMs ship and this world lacked:

  email_template (8 families)  tag (6)  document (5)  event (4)  reminder (4)
  webhook (4)  workflow (4)  address (3)  contract (3)  product_category (3)
  project / project_task (3)  report (3)  dashboard (3)  country (4)

Deliberately NOT added: favorite, link, module, import_map, oauth_token. Those are
application plumbing that happens to survive the framework filter — a favourites
table says nothing about whether a world can run CRM work, and padding the score
with them would be exactly the kind of coverage theatre the honesty rules in
schema-coverage.py exist to prevent.

Every entity gets a full CRUD surface, so the tables are reachable rather than
decorative, and several unlock task families the world could not previously pose:
send-from-template, contract renewal, workflow-rule audit, project delivery.
"""
from __future__ import annotations

import importlib.util
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPECS_DIR = os.path.join(ROOT, "world", "blobfish-wave6", "tool-specs")

# Reuse the op builders rather than restating them.
_p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build-crud-coverage-specs.py")
_s = importlib.util.spec_from_file_location("crudspecs", _p)
_m = importlib.util.module_from_spec(_s)
_s.loader.exec_module(_m)
T, op_list, op_get, op_create, op_update, op_delete, op_search = (
    _m.T, _m.op_list, _m.op_get, _m.op_create, _m.op_update, _m.op_delete, _m.op_search)

MEI, SARAH, ALEX, ROBERT = 1, 2, 3, 4

TABLES = [
    {
        "name": "crm_email_templates",
        "description": "Reusable email templates with merge fields. Modelled by 8 of the 26 "
                       "independent CRM families in the corpus — the most-implemented entity "
                       "this world was missing.",
        "columns": [T("id", pk=True), T("name"), T("subject"), T("body"), T("category"),
                    T("merge_fields"), T("owner_employee_id", "INTEGER"), T("is_active", "INTEGER"),
                    T("times_used", "INTEGER"), T("created_at"), T("updated_at")],
        "sample_rows": [
            {"id": "tmpl_0001", "name": "Discovery Follow-Up", "subject": "Following up on our call, {{contact.first_name}}",
             "body": "Hi {{contact.first_name}},\n\nThanks for the time today. As promised, here is the summary...",
             "category": "prospecting", "merge_fields": "contact.first_name,account.name",
             "owner_employee_id": MEI, "is_active": 1, "times_used": 214,
             "created_at": "2026-01-06T09:00:00Z", "updated_at": "2026-02-01T09:00:00Z"},
            {"id": "tmpl_0002", "name": "Renewal Notice T-120", "subject": "{{account.name}} renewal — 120 day notice",
             "body": "Hi {{contact.first_name}},\n\nYour agreement renews on {{contract.end_date}}...",
             "category": "renewal", "merge_fields": "contact.first_name,account.name,contract.end_date",
             "owner_employee_id": SARAH, "is_active": 1, "times_used": 88,
             "created_at": "2026-01-06T09:00:00Z", "updated_at": "2026-01-30T09:00:00Z"},
            {"id": "tmpl_0003", "name": "Quote Sent", "subject": "Your quote {{quote.id}} is ready",
             "body": "Hi {{contact.first_name}},\n\nPlease find the attached quote for review...",
             "category": "deal", "merge_fields": "contact.first_name,quote.id",
             "owner_employee_id": ROBERT, "is_active": 1, "times_used": 132,
             "created_at": "2026-01-06T09:00:00Z", "updated_at": "2026-02-05T09:00:00Z"},
            {"id": "tmpl_0004", "name": "Win-Back — Closed Lost", "subject": "Checking back in, {{contact.first_name}}",
             "body": "It has been a while since we spoke...", "category": "prospecting",
             "merge_fields": "contact.first_name", "owner_employee_id": MEI, "is_active": 0,
             "times_used": 41, "created_at": "2025-09-01T09:00:00Z", "updated_at": "2025-12-01T09:00:00Z"},
            {"id": "tmpl_0005", "name": "Case Resolved", "subject": "Case {{case.id}} has been resolved",
             "body": "Hi {{contact.first_name}},\n\nWe have resolved your case...", "category": "service",
             "merge_fields": "contact.first_name,case.id", "owner_employee_id": ALEX, "is_active": 1,
             "times_used": 305, "created_at": "2026-01-06T09:00:00Z", "updated_at": "2026-02-08T09:00:00Z"},
            {"id": "tmpl_0006", "name": "Exec Intro — Tier 1", "subject": "Introduction from Morgan Stanley (SIMULATED)",
             "body": "Hi {{contact.first_name}},\n\nI lead our platform team...", "category": "prospecting",
             "merge_fields": "contact.first_name,account.name", "owner_employee_id": ROBERT,
             "is_active": 1, "times_used": 27, "created_at": "2026-01-20T09:00:00Z",
             "updated_at": "2026-02-10T09:00:00Z"},
        ],
    },
    {
        "name": "crm_tags",
        "description": "Free-form labels applied across CRM records. Six independent families model it.",
        "columns": [T("id", pk=True), T("name"), T("color"), T("category"),
                    T("usage_count", "INTEGER"), T("created_at")],
        "sample_rows": [
            {"id": "tag_0001", "name": "strategic", "color": "#1f6feb", "category": "account",
             "usage_count": 14, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "tag_0002", "name": "at-risk", "color": "#d1242f", "category": "account",
             "usage_count": 6, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "tag_0003", "name": "champion", "color": "#1a7f37", "category": "contact",
             "usage_count": 9, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "tag_0004", "name": "do-not-contact", "color": "#6e7781", "category": "contact",
             "usage_count": 3, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "tag_0005", "name": "competitive-displacement", "color": "#bf3989",
             "category": "opportunity", "usage_count": 5, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "tag_0006", "name": "expansion", "color": "#8250df", "category": "opportunity",
             "usage_count": 7, "created_at": "2026-01-06T09:00:00Z"},
        ],
    },
    {
        "name": "crm_tag_assignments",
        "description": "Join table binding a tag to any CRM record.",
        "columns": [T("id", pk=True), T("tag_id"), T("record_type"), T("record_id"),
                    T("assigned_by_employee_id", "INTEGER"), T("assigned_at")],
        "sample_rows": [
            {"id": "tga_0001", "tag_id": "tag_0001", "record_type": "account", "record_id": "account_001",
             "assigned_by_employee_id": MEI, "assigned_at": "2026-01-10T09:00:00Z"},
            {"id": "tga_0002", "tag_id": "tag_0002", "record_type": "account", "record_id": "account_007",
             "assigned_by_employee_id": SARAH, "assigned_at": "2026-02-06T09:00:00Z"},
            {"id": "tga_0003", "tag_id": "tag_0003", "record_type": "contact", "record_id": "contact_006",
             "assigned_by_employee_id": ALEX, "assigned_at": "2026-02-06T09:00:00Z"},
            {"id": "tga_0004", "tag_id": "tag_0001", "record_type": "account", "record_id": "account_002",
             "assigned_by_employee_id": ALEX, "assigned_at": "2026-01-12T09:00:00Z"},
            {"id": "tga_0005", "tag_id": "tag_0004", "record_type": "contact", "record_id": "contact_004",
             "assigned_by_employee_id": MEI, "assigned_at": "2026-01-22T09:00:00Z"},
            {"id": "tga_0006", "tag_id": "tag_0006", "record_type": "account", "record_id": "account_009",
             "assigned_by_employee_id": ALEX, "assigned_at": "2026-02-09T09:00:00Z"},
        ],
    },
    {
        "name": "crm_documents",
        "description": "Document library: proposals, MSAs, security packets and order forms "
                       "attached to CRM records, with revision tracking.",
        "columns": [T("id", pk=True), T("name"), T("document_type"), T("related_type"),
                    T("related_id"), T("revision", "INTEGER"), T("status"), T("file_size", "INTEGER"),
                    T("mime_type"), T("owner_employee_id", "INTEGER"), T("is_confidential", "INTEGER"),
                    T("created_at")],
        "sample_rows": [
            {"id": "doc_0001", "name": "Summit Group — Proposal v3.pdf", "document_type": "proposal",
             "related_type": "account", "related_id": "account_001", "revision": 3, "status": "final",
             "file_size": 482113, "mime_type": "application/pdf", "owner_employee_id": MEI,
             "is_confidential": 0, "created_at": "2026-02-04T09:00:00Z"},
            {"id": "doc_0002", "name": "Riverside — MSA executed.pdf", "document_type": "contract",
             "related_type": "account", "related_id": "account_002", "revision": 1, "status": "executed",
             "file_size": 921004, "mime_type": "application/pdf", "owner_employee_id": ROBERT,
             "is_confidential": 1, "created_at": "2026-02-13T09:00:00Z"},
            {"id": "doc_0003", "name": "Security Packet — SOC2 + pentest.zip", "document_type": "security",
             "related_type": "account", "related_id": "account_002", "revision": 2, "status": "final",
             "file_size": 3341882, "mime_type": "application/zip", "owner_employee_id": ALEX,
             "is_confidential": 1, "created_at": "2026-02-05T09:00:00Z"},
            {"id": "doc_0004", "name": "Ironwood — Order Form draft.docx", "document_type": "order_form",
             "related_type": "account", "related_id": "account_010", "revision": 1, "status": "draft",
             "file_size": 88210, "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
             "owner_employee_id": ROBERT, "is_confidential": 0, "created_at": "2026-02-11T09:00:00Z"},
            {"id": "doc_0005", "name": "Lakeshore — Competitive teardown.pdf", "document_type": "internal",
             "related_type": "account", "related_id": "account_009", "revision": 1, "status": "final",
             "file_size": 210043, "mime_type": "application/pdf", "owner_employee_id": ALEX,
             "is_confidential": 1, "created_at": "2026-02-09T09:00:00Z"},
            {"id": "doc_0006", "name": "FY2026 Price List.xlsx", "document_type": "reference",
             "related_type": "global", "related_id": None, "revision": 4, "status": "final",
             "file_size": 45120, "mime_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
             "owner_employee_id": SARAH, "is_confidential": 0, "created_at": "2026-01-05T09:00:00Z"},
        ],
    },
    {
        "name": "crm_events",
        "description": "Calendar events distinct from customer meetings: internal reviews, "
                       "deadlines and all-day markers.",
        "columns": [T("id", pk=True), T("title"), T("event_type"), T("starts_at"), T("ends_at"),
                    T("all_day", "INTEGER"), T("owner_employee_id", "INTEGER"), T("location"),
                    T("related_type"), T("related_id"), T("status")],
        "sample_rows": [
            {"id": "evt_0001", "title": "Q1 Forecast Review", "event_type": "internal",
             "starts_at": "2026-02-17T16:00:00Z", "ends_at": "2026-02-17T17:00:00Z", "all_day": 0,
             "owner_employee_id": ROBERT, "location": "Board Room", "related_type": None,
             "related_id": None, "status": "confirmed"},
            {"id": "evt_0002", "title": "Quarter end — all deals must be booked", "event_type": "deadline",
             "starts_at": "2026-03-31T00:00:00Z", "ends_at": "2026-03-31T23:59:59Z", "all_day": 1,
             "owner_employee_id": ROBERT, "location": None, "related_type": None, "related_id": None,
             "status": "confirmed"},
            {"id": "evt_0003", "title": "Deal desk office hours", "event_type": "internal",
             "starts_at": "2026-02-18T15:00:00Z", "ends_at": "2026-02-18T16:00:00Z", "all_day": 0,
             "owner_employee_id": SARAH, "location": "Zoom", "related_type": None, "related_id": None,
             "status": "confirmed"},
            {"id": "evt_0004", "title": "Summit Group security review window", "event_type": "milestone",
             "starts_at": "2026-02-24T00:00:00Z", "ends_at": "2026-02-28T23:59:59Z", "all_day": 1,
             "owner_employee_id": MEI, "location": None, "related_type": "account",
             "related_id": "account_001", "status": "tentative"},
            {"id": "evt_0005", "title": "Comp plan rollout", "event_type": "internal",
             "starts_at": "2026-02-20T14:00:00Z", "ends_at": "2026-02-20T15:00:00Z", "all_day": 0,
             "owner_employee_id": ROBERT, "location": "Zoom", "related_type": None, "related_id": None,
             "status": "confirmed"},
        ],
    },
    {
        "name": "crm_reminders",
        "description": "Follow-up reminders bound to a record and an owner.",
        "columns": [T("id", pk=True), T("subject"), T("remind_at"), T("owner_employee_id", "INTEGER"),
                    T("related_type"), T("related_id"), T("status"), T("channel"), T("created_at")],
        "sample_rows": [
            {"id": "rem_0001", "subject": "Chase Riverside security sign-off", "remind_at": "2026-02-18T09:00:00Z",
             "owner_employee_id": ALEX, "related_type": "account", "related_id": "account_002",
             "status": "pending", "channel": "email", "created_at": "2026-02-11T09:00:00Z"},
            {"id": "rem_0002", "subject": "Retry Riverside Services voicemail", "remind_at": "2026-02-16T15:00:00Z",
             "owner_employee_id": SARAH, "related_type": "account", "related_id": "account_007",
             "status": "pending", "channel": "in_app", "created_at": "2026-02-06T09:00:00Z"},
            {"id": "rem_0003", "subject": "Send Ironwood revised pricing", "remind_at": "2026-02-13T09:00:00Z",
             "owner_employee_id": ROBERT, "related_type": "account", "related_id": "account_010",
             "status": "completed", "channel": "email", "created_at": "2026-02-10T09:00:00Z"},
            {"id": "rem_0004", "subject": "Confirm Summit Group budget owner", "remind_at": "2026-02-20T09:00:00Z",
             "owner_employee_id": MEI, "related_type": "account", "related_id": "account_001",
             "status": "pending", "channel": "in_app", "created_at": "2026-02-04T09:00:00Z"},
            {"id": "rem_0005", "subject": "Lakeshore displacement motion — start Q3", "remind_at": "2026-07-01T09:00:00Z",
             "owner_employee_id": ALEX, "related_type": "account", "related_id": "account_009",
             "status": "pending", "channel": "email", "created_at": "2026-02-09T09:00:00Z"},
        ],
    },
    {
        "name": "crm_webhooks",
        "description": "Outbound webhook subscriptions: the integration surface every CRM exposes.",
        "columns": [T("id", pk=True), T("name"), T("target_url"), T("event_types"), T("status"),
                    T("secret_set", "INTEGER"), T("last_delivery_at"), T("failure_count", "INTEGER"),
                    T("created_at")],
        "sample_rows": [
            {"id": "wh_0001", "name": "Billing — order activated", "target_url": "https://billing.internal.example/hooks/orders",
             "event_types": "order.activated,order.cancelled", "status": "active", "secret_set": 1,
             "last_delivery_at": "2026-02-14T11:02:00Z", "failure_count": 0, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "wh_0002", "name": "Data warehouse — opportunity changes",
             "target_url": "https://dw.internal.example/ingest/opportunity",
             "event_types": "opportunity.created,opportunity.updated,opportunity.deleted",
             "status": "active", "secret_set": 1, "last_delivery_at": "2026-02-15T08:40:00Z",
             "failure_count": 0, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "wh_0003", "name": "Legacy CPQ bridge", "target_url": "https://cpq-legacy.internal.example/hook",
             "event_types": "quote.approved", "status": "failing", "secret_set": 1,
             "last_delivery_at": "2026-02-02T09:15:00Z", "failure_count": 41,
             "created_at": "2025-08-01T09:00:00Z"},
            {"id": "wh_0004", "name": "Slack deal alerts", "target_url": "https://hooks.slack.example/services/T0/B0/x",
             "event_types": "opportunity.closed_won", "status": "active", "secret_set": 1,
             "last_delivery_at": "2026-02-13T17:20:00Z", "failure_count": 0,
             "created_at": "2026-01-06T09:00:00Z"},
            {"id": "wh_0005", "name": "Disabled — old marketing sync",
             "target_url": "https://marketing-old.internal.example/sync", "event_types": "lead.created",
             "status": "disabled", "secret_set": 0, "last_delivery_at": "2025-11-30T09:00:00Z",
             "failure_count": 0, "created_at": "2025-03-01T09:00:00Z"},
        ],
    },
    {
        "name": "crm_workflows",
        "description": "Declarative automation rules (trigger, condition, action) — the "
                       "workflow engine four independent CRM families model.",
        "columns": [T("id", pk=True), T("name"), T("object_name"), T("trigger_event"), T("condition_expr"),
                    T("action_type"), T("action_payload"), T("status"), T("run_count", "INTEGER"),
                    T("owner_employee_id", "INTEGER"), T("created_at")],
        "sample_rows": [
            {"id": "wfr_0001", "name": "Route enterprise inbound to AE", "object_name": "Lead",
             "trigger_event": "on_create", "condition_expr": "lead.estimated_value >= 100000",
             "action_type": "assign_owner", "action_payload": "{\"owner_employee_id\": 4}",
             "status": "active", "run_count": 212, "owner_employee_id": ROBERT,
             "created_at": "2026-01-06T09:00:00Z"},
            {"id": "wfr_0002", "name": "Flag discount above policy", "object_name": "Quote",
             "trigger_event": "on_update", "condition_expr": "quote.discount_pct > 25",
             "action_type": "require_approval", "action_payload": "{\"approver_role\": \"Finance\"}",
             "status": "active", "run_count": 47, "owner_employee_id": SARAH,
             "created_at": "2026-01-06T09:00:00Z"},
            {"id": "wfr_0003", "name": "Renewal reminder at T-120", "object_name": "Contract",
             "trigger_event": "scheduled", "condition_expr": "contract.end_date <= now + 120d",
             "action_type": "create_reminder", "action_payload": "{\"template_id\": \"tmpl_0002\"}",
             "status": "active", "run_count": 88, "owner_employee_id": SARAH,
             "created_at": "2026-01-06T09:00:00Z"},
            {"id": "wfr_0004", "name": "Suppress bounced contacts", "object_name": "Contact",
             "trigger_event": "on_update", "condition_expr": "contact.email IN bounces",
             "action_type": "set_field", "action_payload": "{\"Do_Not_Sequence__c\": true}",
             "status": "active", "run_count": 87, "owner_employee_id": MEI,
             "created_at": "2026-01-06T09:00:00Z"},
            {"id": "wfr_0005", "name": "Auto-close stale opportunities", "object_name": "Opportunity",
             "trigger_event": "scheduled", "condition_expr": "opportunity.last_activity_at < now - 180d",
             "action_type": "set_field", "action_payload": "{\"status\": \"closed_lost\"}",
             "status": "paused", "run_count": 0, "owner_employee_id": ROBERT,
             "created_at": "2026-01-15T09:00:00Z"},
        ],
    },
    {
        "name": "crm_contracts",
        "description": "Signed customer agreements with term, value and renewal posture.",
        "columns": [T("id", pk=True), T("account_id"), T("contract_number"), T("status"),
                    T("start_date"), T("end_date"), T("term_months", "INTEGER"),
                    T("total_value", "REAL"), T("currency"), T("auto_renew", "INTEGER"),
                    T("notice_days", "INTEGER"), T("owner_employee_id", "INTEGER"), T("signed_at")],
        "sample_rows": [
            {"id": "ctr_0001", "account_id": "account_001", "contract_number": "MS-2025-0041",
             "status": "active", "start_date": "2025-04-01", "end_date": "2026-03-31", "term_months": 12,
             "total_value": 142000.0, "currency": "usd", "auto_renew": 1, "notice_days": 90,
             "owner_employee_id": MEI, "signed_at": "2025-03-18T09:00:00Z"},
            {"id": "ctr_0002", "account_id": "account_002", "contract_number": "MS-2026-0002",
             "status": "active", "start_date": "2026-02-13", "end_date": "2029-02-12", "term_months": 36,
             "total_value": 708000.0, "currency": "usd", "auto_renew": 0, "notice_days": 120,
             "owner_employee_id": ROBERT, "signed_at": "2026-02-13T09:00:00Z"},
            {"id": "ctr_0003", "account_id": "account_007", "contract_number": "MS-2025-0088",
             "status": "expiring", "start_date": "2025-03-01", "end_date": "2026-02-28", "term_months": 12,
             "total_value": 84000.0, "currency": "eur", "auto_renew": 0, "notice_days": 60,
             "owner_employee_id": SARAH, "signed_at": "2025-02-14T09:00:00Z"},
            {"id": "ctr_0004", "account_id": "account_009", "contract_number": "MS-2024-0203",
             "status": "expired", "start_date": "2024-01-01", "end_date": "2025-12-31", "term_months": 24,
             "total_value": 96000.0, "currency": "usd", "auto_renew": 0, "notice_days": 30,
             "owner_employee_id": ALEX, "signed_at": "2023-12-11T09:00:00Z"},
            {"id": "ctr_0005", "account_id": "account_005", "contract_number": "MS-2026-0007",
             "status": "pending_signature", "start_date": "2026-03-01", "end_date": "2027-02-28",
             "term_months": 12, "total_value": 61000.0, "currency": "gbp", "auto_renew": 1,
             "notice_days": 90, "owner_employee_id": SARAH, "signed_at": None},
        ],
    },
    {
        "name": "crm_product_categories",
        "description": "Product family hierarchy used for catalogue browsing and reporting.",
        "columns": [T("id", pk=True), T("name"), T("parent_id"), T("display_order", "INTEGER"),
                    T("is_active", "INTEGER"), T("description")],
        "sample_rows": [
            {"id": "pcat_0001", "name": "Platform", "parent_id": None, "display_order": 1,
             "is_active": 1, "description": "Core Atlas platform licences."},
            {"id": "pcat_0002", "name": "Market Data", "parent_id": None, "display_order": 2,
             "is_active": 1, "description": "Real-time and delayed market data feeds."},
            {"id": "pcat_0003", "name": "Analytics", "parent_id": None, "display_order": 3,
             "is_active": 1, "description": "Risk and portfolio analytics modules."},
            {"id": "pcat_0004", "name": "Support", "parent_id": None, "display_order": 4,
             "is_active": 1, "description": "Support and success plans."},
            {"id": "pcat_0005", "name": "Level 2 Feeds", "parent_id": "pcat_0002", "display_order": 1,
             "is_active": 1, "description": "Depth-of-book feeds."},
            {"id": "pcat_0006", "name": "Legacy", "parent_id": None, "display_order": 9,
             "is_active": 0, "description": "End-of-life SKUs retained for renewals only."},
        ],
    },
    {
        "name": "crm_addresses",
        "description": "Normalised postal addresses attached to accounts and contacts.",
        "columns": [T("id", pk=True), T("related_type"), T("related_id"), T("address_type"),
                    T("line1"), T("line2"), T("city"), T("state"), T("postal_code"),
                    T("country_code"), T("is_primary", "INTEGER")],
        "sample_rows": [
            {"id": "addr_0001", "related_type": "account", "related_id": "account_001",
             "address_type": "billing", "line1": "200 West Street", "line2": "Floor 34",
             "city": "New York", "state": "NY", "postal_code": "10282", "country_code": "US",
             "is_primary": 1},
            {"id": "addr_0002", "related_type": "account", "related_id": "account_002",
             "address_type": "billing", "line1": "1 Riverside Plaza", "line2": None,
             "city": "Chicago", "state": "IL", "postal_code": "60606", "country_code": "US",
             "is_primary": 1},
            {"id": "addr_0003", "related_type": "account", "related_id": "account_002",
             "address_type": "shipping", "line1": "1 Riverside Plaza", "line2": "Dock B",
             "city": "Chicago", "state": "IL", "postal_code": "60606", "country_code": "US",
             "is_primary": 0},
            {"id": "addr_0004", "related_type": "account", "related_id": "account_007",
             "address_type": "billing", "line1": "25 Bishopsgate", "line2": None, "city": "London",
             "state": None, "postal_code": "EC2N 4AJ", "country_code": "GB", "is_primary": 1},
            {"id": "addr_0005", "related_type": "account", "related_id": "account_009",
             "address_type": "billing", "line1": "Marienplatz 8", "line2": None, "city": "Munich",
             "state": None, "postal_code": "80331", "country_code": "DE", "is_primary": 1},
        ],
    },
    {
        "name": "crm_countries",
        "description": "ISO country reference data with the region and currency defaults that "
                       "territory and pricing rules key off.",
        "columns": [T("code", pk=True), T("name"), T("region"), T("default_currency"),
                    T("is_sales_territory", "INTEGER"), T("data_residency_required", "INTEGER")],
        "sample_rows": [
            {"code": "US", "name": "United States", "region": "NA", "default_currency": "usd",
             "is_sales_territory": 1, "data_residency_required": 0},
            {"code": "GB", "name": "United Kingdom", "region": "EMEA", "default_currency": "gbp",
             "is_sales_territory": 1, "data_residency_required": 0},
            {"code": "DE", "name": "Germany", "region": "EMEA", "default_currency": "eur",
             "is_sales_territory": 1, "data_residency_required": 1},
            {"code": "FR", "name": "France", "region": "EMEA", "default_currency": "eur",
             "is_sales_territory": 1, "data_residency_required": 1},
            {"code": "SG", "name": "Singapore", "region": "APAC", "default_currency": "sgd",
             "is_sales_territory": 1, "data_residency_required": 1},
            {"code": "JP", "name": "Japan", "region": "APAC", "default_currency": "jpy",
             "is_sales_territory": 1, "data_residency_required": 1},
            {"code": "CA", "name": "Canada", "region": "NA", "default_currency": "cad",
             "is_sales_territory": 1, "data_residency_required": 0},
            {"code": "AU", "name": "Australia", "region": "APAC", "default_currency": "aud",
             "is_sales_territory": 1, "data_residency_required": 0},
        ],
    },
    {
        "name": "crm_projects",
        "description": "Delivery/onboarding projects opened after a deal closes.",
        "columns": [T("id", pk=True), T("name"), T("account_id"), T("status"), T("health"),
                    T("start_date"), T("target_end_date"), T("owner_employee_id", "INTEGER"),
                    T("percent_complete", "INTEGER"), T("budget", "REAL")],
        "sample_rows": [
            {"id": "prj_0001", "name": "Summit Group — Platform onboarding", "account_id": "account_001",
             "status": "in_progress", "health": "green", "start_date": "2026-01-15",
             "target_end_date": "2026-03-15", "owner_employee_id": ALEX, "percent_complete": 60,
             "budget": 45000.0},
            {"id": "prj_0002", "name": "Riverside — Market data rollout", "account_id": "account_002",
             "status": "in_progress", "health": "amber", "start_date": "2026-02-01",
             "target_end_date": "2026-04-30", "owner_employee_id": ALEX, "percent_complete": 25,
             "budget": 88000.0},
            {"id": "prj_0003", "name": "Riverside Services — Migration", "account_id": "account_007",
             "status": "at_risk", "health": "red", "start_date": "2025-11-01",
             "target_end_date": "2026-02-28", "owner_employee_id": SARAH, "percent_complete": 40,
             "budget": 30000.0},
            {"id": "prj_0004", "name": "Lakeshore Systems — Pilot", "account_id": "account_009",
             "status": "completed", "health": "green", "start_date": "2025-09-01",
             "target_end_date": "2025-12-15", "owner_employee_id": ALEX, "percent_complete": 100,
             "budget": 12000.0},
        ],
    },
    {
        "name": "crm_project_tasks",
        "description": "Work items inside a delivery project, with dependencies and effort.",
        "columns": [T("id", pk=True), T("project_id"), T("name"), T("status"), T("assigned_to", "INTEGER"),
                    T("due_date"), T("depends_on"), T("estimated_hours", "REAL"), T("actual_hours", "REAL")],
        "sample_rows": [
            {"id": "ptask_0001", "project_id": "prj_0001", "name": "SSO configuration",
             "status": "completed", "assigned_to": ALEX, "due_date": "2026-01-30", "depends_on": None,
             "estimated_hours": 16.0, "actual_hours": 14.5},
            {"id": "ptask_0002", "project_id": "prj_0001", "name": "Data migration dry run",
             "status": "in_progress", "assigned_to": ALEX, "due_date": "2026-02-20",
             "depends_on": "ptask_0001", "estimated_hours": 40.0, "actual_hours": 22.0},
            {"id": "ptask_0003", "project_id": "prj_0001", "name": "User training",
             "status": "not_started", "assigned_to": SARAH, "due_date": "2026-03-10",
             "depends_on": "ptask_0002", "estimated_hours": 12.0, "actual_hours": None},
            {"id": "ptask_0004", "project_id": "prj_0002", "name": "Feed entitlement review",
             "status": "blocked", "assigned_to": ALEX, "due_date": "2026-02-18", "depends_on": None,
             "estimated_hours": 8.0, "actual_hours": 3.0},
            {"id": "ptask_0005", "project_id": "prj_0003", "name": "Legacy export validation",
             "status": "in_progress", "assigned_to": SARAH, "due_date": "2026-02-14",
             "depends_on": None, "estimated_hours": 24.0, "actual_hours": 31.0},
        ],
    },
    {
        "name": "crm_reports",
        "description": "Saved report definitions — the reporting surface three independent families model.",
        "columns": [T("id", pk=True), T("name"), T("object_name"), T("report_type"), T("filter_expr"),
                    T("group_by"), T("metrics"), T("owner_employee_id", "INTEGER"), T("is_scheduled", "INTEGER"),
                    T("schedule_cron"), T("last_run_at")],
        "sample_rows": [
            {"id": "rpt_0001", "name": "Pipeline by Stage", "object_name": "Opportunity",
             "report_type": "summary", "filter_expr": "status NOT IN ('closed_won','closed_lost')",
             "group_by": "status", "metrics": "count,sum(amount)", "owner_employee_id": ROBERT,
             "is_scheduled": 1, "schedule_cron": "0 8 * * MON", "last_run_at": "2026-02-16T08:00:00Z"},
            {"id": "rpt_0002", "name": "Quota Attainment by Rep", "object_name": "RepQuota",
             "report_type": "matrix", "filter_expr": "period = 'FY2026-Q1'", "group_by": "employee_name",
             "metrics": "sum(attainment_amount),sum(quota_amount)", "owner_employee_id": ROBERT,
             "is_scheduled": 1, "schedule_cron": "0 7 * * *", "last_run_at": "2026-02-16T07:00:00Z"},
            {"id": "rpt_0003", "name": "Cases Breaching SLA", "object_name": "Case",
             "report_type": "tabular", "filter_expr": "sla_breached = 1", "group_by": None,
             "metrics": "count", "owner_employee_id": ALEX, "is_scheduled": 0, "schedule_cron": None,
             "last_run_at": "2026-02-15T13:20:00Z"},
            {"id": "rpt_0004", "name": "Discount Exceptions", "object_name": "Quote",
             "report_type": "tabular", "filter_expr": "discount_pct > 25", "group_by": None,
             "metrics": "count,avg(discount_pct)", "owner_employee_id": SARAH, "is_scheduled": 1,
             "schedule_cron": "0 9 * * FRI", "last_run_at": "2026-02-13T09:00:00Z"},
        ],
    },
    {
        "name": "crm_dashboards",
        "description": "Dashboards composing saved reports for a role.",
        "columns": [T("id", pk=True), T("name"), T("owner_employee_id", "INTEGER"), T("audience_role"),
                    T("report_ids"), T("layout"), T("is_default", "INTEGER"), T("created_at")],
        "sample_rows": [
            {"id": "dash_0001", "name": "Sales Leadership", "owner_employee_id": ROBERT,
             "audience_role": "VP Sales", "report_ids": "rpt_0001,rpt_0002", "layout": "2-column",
             "is_default": 1, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "dash_0002", "name": "Deal Desk", "owner_employee_id": SARAH,
             "audience_role": "Deal Desk", "report_ids": "rpt_0004", "layout": "1-column",
             "is_default": 0, "created_at": "2026-01-06T09:00:00Z"},
            {"id": "dash_0003", "name": "Support Operations", "owner_employee_id": ALEX,
             "audience_role": "Support Manager", "report_ids": "rpt_0003", "layout": "1-column",
             "is_default": 0, "created_at": "2026-01-06T09:00:00Z"},
        ],
    },
]


def tools():
    """A full CRUD surface per entity, so the tables are reachable, not decorative."""
    t = []
    t += [
        op_list("email_templates_list", "List email templates (GET /crm/v3/objects/email_templates).",
                "crm_email_templates", ["category", "is_active", "owner_employee_id"]),
        op_get("email_template_get", "Retrieve one email template (GET /crm/v3/objects/email_templates/{id}).",
               "crm_email_templates", "template_id"),
        op_create("email_template_create", "Create an email template (POST /crm/v3/objects/email_templates).",
                  "crm_email_templates", ["name", "subject", "body", "category", "merge_fields",
                                          "owner_employee_id"], required=["name", "subject", "body"],
                  defaults={"is_active": 1, "times_used": 0}, id_prefix="tmpl_"),
        op_update("email_template_update", "Update an email template (PATCH /crm/v3/objects/email_templates/{id}).",
                  "crm_email_templates", "template_id",
                  ["name", "subject", "body", "category", "merge_fields", "is_active", "updated_at"]),
        op_delete("email_template_delete", "Delete an email template (DELETE /crm/v3/objects/email_templates/{id}).",
                  "crm_email_templates", "template_id"),
        op_search("email_templates_search", "Search templates by name, subject or body (POST /crm/v3/objects/email_templates/search).",
                  "crm_email_templates", ["name", "subject", "body"], filters=["category"]),

        op_list("tags_list", "List tags (GET /crm/v3/objects/tags).", "crm_tags", ["category"]),
        op_create("tag_create", "Create a tag (POST /crm/v3/objects/tags).", "crm_tags",
                  ["name", "color", "category"], required=["name"], defaults={"usage_count": 0},
                  id_prefix="tag_"),
        op_update("tag_update", "Rename or recolour a tag (PATCH /crm/v3/objects/tags/{id}).",
                  "crm_tags", "tag_id", ["name", "color", "category", "usage_count"]),
        op_delete("tag_delete", "Delete a tag (DELETE /crm/v3/objects/tags/{id}).", "crm_tags", "tag_id"),
        op_list("tag_assignments_list", "List tag assignments (GET /crm/v3/objects/tags/assignments).",
                "crm_tag_assignments", ["tag_id", "record_type", "record_id"]),
        op_create("tag_assign", "Apply a tag to a record (POST /crm/v3/objects/tags/assignments).",
                  "crm_tag_assignments", ["tag_id", "record_type", "record_id", "assigned_by_employee_id"],
                  required=["tag_id", "record_type", "record_id"], id_prefix="tga_"),
        op_delete("tag_unassign", "Remove a tag assignment (DELETE /crm/v3/objects/tags/assignments/{id}).",
                  "crm_tag_assignments", "assignment_id"),

        op_list("documents_list", "List documents (GET /crm/v3/objects/documents).", "crm_documents",
                ["related_type", "related_id", "document_type", "status", "is_confidential"]),
        op_get("document_get", "Retrieve document metadata (GET /crm/v3/objects/documents/{id}).",
               "crm_documents", "document_id"),
        op_create("document_create", "Register a document (POST /crm/v3/objects/documents).", "crm_documents",
                  ["name", "document_type", "related_type", "related_id", "mime_type", "file_size",
                   "owner_employee_id", "is_confidential"], required=["name", "document_type"],
                  defaults={"revision": 1, "status": "draft"}, id_prefix="doc_"),
        op_update("document_update", "Update document metadata or revision (PATCH /crm/v3/objects/documents/{id}).",
                  "crm_documents", "document_id", ["name", "status", "revision", "is_confidential",
                                                   "document_type"]),
        op_delete("document_delete", "Delete a document (DELETE /crm/v3/objects/documents/{id}).",
                  "crm_documents", "document_id"),
        op_search("documents_search", "Search documents by name (POST /crm/v3/objects/documents/search).",
                  "crm_documents", ["name"], filters=["document_type", "status"]),

        op_list("events_list", "List calendar events (GET /crm/v3/objects/events).",
                "crm_events", ["event_type", "owner_employee_id", "status"]),
        op_get("event_get", "Retrieve one calendar event (GET /crm/v3/objects/events/{id}).",
               "crm_events", "event_id"),
        op_create("event_create", "Create a calendar event (POST /crm/v3/objects/events).",
                  "crm_events", ["title", "event_type", "starts_at", "ends_at", "all_day",
                                          "owner_employee_id", "location", "related_type", "related_id"],
                  required=["title", "starts_at"], defaults={"status": "confirmed"}, id_prefix="evt_"),
        op_update("event_update", "Update a calendar event (PATCH /crm/v3/objects/events/{id}).",
                  "crm_events", "event_id",
                  ["title", "starts_at", "ends_at", "all_day", "location", "status", "event_type"]),
        op_delete("event_delete", "Delete a calendar event (DELETE /crm/v3/objects/events/{id}).",
                  "crm_events", "event_id"),

        op_list("reminders_list", "List reminders (GET /crm/v3/objects/reminders).", "crm_reminders",
                ["owner_employee_id", "status", "related_type", "related_id"]),
        op_get("reminder_get", "Retrieve one reminder (GET /crm/v3/objects/reminders/{id}).",
               "crm_reminders", "reminder_id"),
        op_create("reminder_create", "Create a reminder (POST /crm/v3/objects/reminders).", "crm_reminders",
                  ["subject", "remind_at", "owner_employee_id", "related_type", "related_id", "channel"],
                  required=["subject", "remind_at"], defaults={"status": "pending"}, id_prefix="rem_"),
        op_update("reminder_update", "Update or complete a reminder (PATCH /crm/v3/objects/reminders/{id}).",
                  "crm_reminders", "reminder_id", ["subject", "remind_at", "status", "channel"]),
        op_delete("reminder_delete", "Delete a reminder (DELETE /crm/v3/objects/reminders/{id}).",
                  "crm_reminders", "reminder_id"),

        op_list("webhooks_list", "List webhook subscriptions (GET /webhooks/v3/subscriptions).",
                "crm_webhooks", ["status"]),
        op_get("webhook_get", "Retrieve a webhook subscription (GET /webhooks/v3/subscriptions/{id}).",
               "crm_webhooks", "webhook_id"),
        op_create("webhook_create", "Create a webhook subscription (POST /webhooks/v3/subscriptions).",
                  "crm_webhooks", ["name", "target_url", "event_types", "secret_set"],
                  required=["name", "target_url", "event_types"],
                  defaults={"status": "active", "failure_count": 0}, id_prefix="wh_"),
        op_update("webhook_update", "Update a webhook subscription (PATCH /webhooks/v3/subscriptions/{id}).",
                  "crm_webhooks", "webhook_id", ["name", "target_url", "event_types", "status"]),
        op_delete("webhook_delete", "Delete a webhook subscription (DELETE /webhooks/v3/subscriptions/{id}).",
                  "crm_webhooks", "webhook_id"),

        op_list("workflows_list", "List workflow automation rules (GET /automation/v4/workflows).",
                "crm_workflows", ["object_name", "status", "trigger_event"]),
        op_get("workflow_get", "Retrieve one workflow rule (GET /automation/v4/workflows/{id}).",
               "crm_workflows", "rule_id"),
        op_create("workflow_create", "Create a workflow rule (POST /automation/v4/workflows).",
                  "crm_workflows", ["name", "object_name", "trigger_event", "condition_expr",
                                         "action_type", "action_payload", "owner_employee_id"],
                  required=["name", "object_name", "trigger_event", "action_type"],
                  defaults={"status": "draft", "run_count": 0}, id_prefix="wfr_"),
        op_update("workflow_update", "Update or pause a workflow rule (PATCH /automation/v4/workflows/{id}).",
                  "crm_workflows", "rule_id",
                  ["name", "condition_expr", "action_type", "action_payload", "status"]),
        op_delete("workflow_delete", "Delete a workflow rule (DELETE /automation/v4/workflows/{id}).",
                  "crm_workflows", "rule_id"),

        op_list("contracts_list", "List contracts (GET /crm/v3/objects/contracts).", "crm_contracts",
                ["account_id", "status", "owner_employee_id"]),
        op_get("contract_get", "Retrieve one contract (GET /crm/v3/objects/contracts/{id}).",
               "crm_contracts", "contract_id"),
        op_create("contract_create", "Create a contract (POST /crm/v3/objects/contracts).", "crm_contracts",
                  ["account_id", "contract_number", "start_date", "end_date", "term_months",
                   "total_value", "currency", "auto_renew", "notice_days", "owner_employee_id"],
                  required=["account_id", "contract_number", "start_date", "end_date"],
                  defaults={"status": "draft"}, id_prefix="ctr_"),
        op_update("contract_update", "Update a contract (PATCH /crm/v3/objects/contracts/{id}).",
                  "crm_contracts", "contract_id",
                  ["status", "end_date", "term_months", "total_value", "auto_renew", "notice_days",
                   "signed_at"]),
        op_delete("contract_delete", "Delete a contract (DELETE /crm/v3/objects/contracts/{id}).",
                  "crm_contracts", "contract_id"),

        op_list("product_categories_list", "List product categories (GET /crm/v3/objects/product_categories).",
                "crm_product_categories", ["parent_id", "is_active"]),
        op_create("product_category_create", "Create a product category (POST /crm/v3/objects/product_categories).",
                  "crm_product_categories", ["name", "parent_id", "display_order", "description"],
                  required=["name"], defaults={"is_active": 1}, id_prefix="pcat_"),
        op_update("product_category_update", "Update a product category (PATCH /crm/v3/objects/product_categories/{id}).",
                  "crm_product_categories", "category_id",
                  ["name", "parent_id", "display_order", "is_active", "description"]),
        op_delete("product_category_delete", "Delete a product category (DELETE /crm/v3/objects/product_categories/{id}).",
                  "crm_product_categories", "category_id"),

        op_list("addresses_list", "List addresses (GET /crm/v3/objects/addresses).", "crm_addresses",
                ["related_type", "related_id", "address_type", "country_code"]),
        op_create("address_create", "Attach an address to a record (POST /crm/v3/objects/addresses).",
                  "crm_addresses", ["related_type", "related_id", "address_type", "line1", "line2",
                                    "city", "state", "postal_code", "country_code", "is_primary"],
                  required=["related_type", "related_id", "line1", "country_code"], id_prefix="addr_"),
        op_update("address_update", "Update an address (PATCH /crm/v3/objects/addresses/{id}).",
                  "crm_addresses", "address_id",
                  ["line1", "line2", "city", "state", "postal_code", "country_code", "is_primary",
                   "address_type"]),
        op_delete("address_delete", "Delete an address (DELETE /crm/v3/objects/addresses/{id}).",
                  "crm_addresses", "address_id"),

        op_list("countries_list", "List country reference data (GET /crm/v3/properties/countries).",
                "crm_countries", ["region", "is_sales_territory", "data_residency_required"]),
        op_get("country_get", "Retrieve one country by ISO code (GET /crm/v3/properties/countries/{code}).",
               "crm_countries", "country_code", id_column="code"),

        op_list("projects_list", "List delivery projects (GET /crm/v3/objects/projects).", "crm_projects",
                ["account_id", "status", "health", "owner_employee_id"]),
        op_get("project_get", "Retrieve one project (GET /crm/v3/objects/projects/{id}).",
               "crm_projects", "project_id"),
        op_create("project_create", "Open a delivery project (POST /crm/v3/objects/projects).",
                  "crm_projects", ["name", "account_id", "start_date", "target_end_date",
                                   "owner_employee_id", "budget"], required=["name", "account_id"],
                  defaults={"status": "not_started", "health": "green", "percent_complete": 0},
                  id_prefix="prj_"),
        op_update("project_update", "Update project status or health (PATCH /crm/v3/objects/projects/{id}).",
                  "crm_projects", "project_id",
                  ["name", "status", "health", "target_end_date", "percent_complete", "budget"]),
        op_delete("project_delete", "Delete a project (DELETE /crm/v3/objects/projects/{id}).",
                  "crm_projects", "project_id"),
        op_list("project_tasks_list", "List tasks in a project (GET /crm/v3/objects/projects/{id}/tasks).",
                "crm_project_tasks", ["project_id", "status", "assigned_to"]),
        op_create("project_task_create", "Add a task to a project (POST /crm/v3/objects/projects/{id}/tasks).",
                  "crm_project_tasks", ["project_id", "name", "assigned_to", "due_date", "depends_on",
                                        "estimated_hours"], required=["project_id", "name"],
                  defaults={"status": "not_started"}, id_prefix="ptask_"),
        op_update("project_task_update", "Update a project task (PATCH /crm/v3/objects/projects/tasks/{id}).",
                  "crm_project_tasks", "task_id",
                  ["name", "status", "assigned_to", "due_date", "depends_on", "estimated_hours",
                   "actual_hours"]),
        op_delete("project_task_delete", "Delete a project task (DELETE /crm/v3/objects/projects/tasks/{id}).",
                  "crm_project_tasks", "task_id"),

        op_list("reports_list", "List saved reports (GET /crm/v3/reports).", "crm_reports",
                ["object_name", "owner_employee_id", "is_scheduled"]),
        op_get("report_get", "Retrieve a saved report definition (GET /crm/v3/reports/{id}).",
               "crm_reports", "report_id"),
        op_create("report_create", "Create a saved report (POST /crm/v3/reports).", "crm_reports",
                  ["name", "object_name", "report_type", "filter_expr", "group_by", "metrics",
                   "owner_employee_id", "schedule_cron"], required=["name", "object_name"],
                  defaults={"is_scheduled": 0}, id_prefix="rpt_"),
        op_update("report_update", "Update a saved report (PATCH /crm/v3/reports/{id}).", "crm_reports",
                  "report_id", ["name", "filter_expr", "group_by", "metrics", "is_scheduled",
                                "schedule_cron", "last_run_at"]),
        op_delete("report_delete", "Delete a saved report (DELETE /crm/v3/reports/{id}).",
                  "crm_reports", "report_id"),

        op_list("dashboards_list", "List dashboards (GET /crm/v3/dashboards).", "crm_dashboards",
                ["owner_employee_id", "audience_role"]),
        op_get("dashboard_get", "Retrieve a dashboard (GET /crm/v3/dashboards/{id}).",
               "crm_dashboards", "dashboard_id"),
        op_create("dashboard_create", "Create a dashboard (POST /crm/v3/dashboards).", "crm_dashboards",
                  ["name", "owner_employee_id", "audience_role", "report_ids", "layout"],
                  required=["name"], defaults={"is_default": 0}, id_prefix="dash_"),
        op_update("dashboard_update", "Update a dashboard (PATCH /crm/v3/dashboards/{id}).",
                  "crm_dashboards", "dashboard_id",
                  ["name", "audience_role", "report_ids", "layout", "is_default"]),
        op_delete("dashboard_delete", "Delete a dashboard (DELETE /crm/v3/dashboards/{id}).",
                  "crm_dashboards", "dashboard_id"),
    ]
    return t


def main():
    spec = {"vendor": "salesforce-crm", "namespace": "salesforce",
            "tables": TABLES, "tools": tools()}
    path = os.path.join(SPECS_DIR, "crm-entity-coverage.json")
    with open(path, "w") as f:
        json.dump(spec, f, indent=1, ensure_ascii=False)
        f.write("\n")
    print(f"wrote tool-specs/crm-entity-coverage.json: "
          f"{len(spec['tools'])} tools, {len(spec['tables'])} tables")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
