#!/usr/bin/env python3
"""Measure how much of the sales-task domain actually has a runnable task.

    python3 scripts/task-coverage.py [--out docs/TASK-COVERAGE-MEASURED.md]

The project's goal is a single world that mocks every sales task worth testing.
`TOOL-COVERAGE.md` proves the verbs exist and `SCHEMA-COVERAGE.md` proves the data
model exists; neither says whether an agent can be *asked* to do the work. This does.

Demand side: the 79 eval-task items in `data/coverage/census-items.json`, minus the
ones judged out of scope, leaving 68 in-scope items enumerated from CRMArena,
CRMArena-Pro, tau-bench-class benchmarks, the AI-SDR ecosystem and the trust/safety
evals.

Supply side: the tasks that exist, mapped to census items by
`data/coverage/task-census-map.json` — an explicit, hand-maintained map. Fuzzy name
matching was rejected deliberately: `case_routing` and `lead_routing` share a token,
and a coverage number that drifts on a keyword collision is worth nothing. A task
covers an item when someone decided it does.

Suites are reported separately because they are not equivalent evidence. A
`sales-world` task is graded by state assertions against the world an agent mutated;
a `crmarena` task reproduces CRMArena's own single-answer exact/fuzzy metric on a
separate parity world. Both are real, and collapsing them into one number would hide
that the second does not yet run on the single world.
"""
from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
COV = ROOT / "data" / "coverage"
TASKS = ROOT / "tasks"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(ROOT / "docs" / "TASK-COVERAGE-MEASURED.md"))
    args = ap.parse_args()

    items = json.loads((COV / "census-items.json").read_text())
    verdicts = {v["name"]: v["verdict"] for v in json.loads((COV / "verdicts.json").read_text())}
    cmap = json.loads((COV / "task-census-map.json").read_text())
    covers = cmap["covers"]

    in_scope = [i for i in items
                if i["kind"] == "eval_task" and verdicts.get(i["name"]) != "out_of_scope"]
    census = {i["name"]: i for i in in_scope}

    # ---- which tasks actually exist on disk
    sales = sorted(d.name for d in (TASKS / "sales-world").iterdir() if d.is_dir()) \
        if (TASKS / "sales-world").is_dir() else []
    crm_dirs = sorted(d.name for d in (TASKS / "crmarena").iterdir() if d.is_dir()) \
        if (TASKS / "crmarena").is_dir() else []
    # crmarena task dirs are <category>_<id>; collapse to the category the map keys on
    crm_cats = sorted({"_".join(d.split("_")[:-1]) for d in crm_dirs})

    by_item: dict[str, list[tuple[str, str]]] = defaultdict(list)
    unmapped = []
    for tid in sales:
        if tid not in covers:
            unmapped.append(("sales-world", tid))
            continue
        for item in covers[tid]:
            by_item[item].append(("sales-world", tid))
    for cat in crm_cats:
        if cat not in covers:
            unmapped.append(("crmarena", cat))
            continue
        for item in covers[cat]:
            by_item[item].append(("crmarena", cat))

    # A mapped item that is not in the census is a stale map entry, not coverage.
    stale = sorted({i for v in covers.values() for i in v} - set(census))

    covered = {n for n in census if by_item.get(n)}
    state_verified = {n for n in covered if any(s == "sales-world" for s, _ in by_item[n])}
    answer_only = covered - state_verified
    missing = sorted(set(census) - covered)

    pct = 100 * len(covered) / max(1, len(census))
    out = [
        "# Task coverage — how much of the domain can an agent actually be asked to do",
        "",
        "Generated by `scripts/task-coverage.py`. `TOOL-COVERAGE.md` proves the verbs exist and",
        "`SCHEMA-COVERAGE.md` proves the data model exists. Neither says whether the work can be",
        "*posed* as a task. This does, from an explicit map; the hand-written companion",
        "`TASK-COVERAGE.md` reasons category-by-category over the CRMArena/Pro surface.",
        "",
        f"- in-scope eval-task census items: **{len(census)}**",
        f"- with at least one runnable task: **{len(covered)}** ({pct:.0f}%)",
        f"-   of those, state-verified on the single world: **{len(state_verified)}**",
        f"-   answer-metric only (crmarena parity world): **{len(answer_only)}**",
        f"- with no task at all: **{len(missing)}**",
        "",
        f"Tasks on disk: **{len(sales)}** in `tasks/sales-world`, "
        f"**{len(crm_dirs)}** in `tasks/crmarena` across {len(crm_cats)} categories.",
        "",
        "The two suites are counted separately on purpose. A `sales-world` task is graded by state",
        "assertions against a world the agent mutated, with collateral checks that fail a destructive",
        "shortcut. A `crmarena` task reproduces CRMArena's single-answer exact/fuzzy metric and today",
        "runs on a separate parity world. Both are real evidence; merging them into one number would",
        "hide that the second does not yet run on the single world.",
        "",
        "## Not yet posable",
        "",
        f"{len(missing)} in-scope census items have no task. This is the authoring backlog, printed in",
        "full — a truncated backlog reads as coverage that was never earned.",
        "",
        "| census item | verdict on substrate | source |",
        "|---|---|---|",
    ]
    for n in missing:
        it = census[n]
        src = str(it.get("source") or it.get("source_class") or "")[:64]
        out.append(f"| `{n}` | {verdicts.get(n, '?')} | {src} |")

    out += ["", "## Covered", "", "| census item | by |", "|---|---|"]
    for n in sorted(covered):
        who = ", ".join(f"`{t}` ({s})" for s, t in by_item[n])
        out.append(f"| `{n}` | {who} |")

    if unmapped:
        out += ["", "## Tasks with no census entry", "",
                "Real work the census does not enumerate. Listed rather than stretched onto a",
                "neighbouring item to inflate the number.", ""]
        for suite, tid in unmapped:
            note = cmap.get("notes", {}).get(tid, "")
            out.append(f"- `{tid}` ({suite})" + (f" — {note}" if note else ""))

    if stale:
        out += ["", "## Stale map entries", "",
                "Mapped to a census item that does not exist or is out of scope. Fix the map.", ""]
        out += [f"- `{s}`" for s in stale]

    out.append("")
    Path(args.out).write_text("\n".join(out))
    print(f"census in-scope {len(census)} | covered {len(covered)} ({pct:.0f}%) | "
          f"state-verified {len(state_verified)} | answer-only {len(answer_only)} | missing {len(missing)}")
    if unmapped:
        print(f"tasks with no census entry: {len(unmapped)}")
    if stale:
        print(f"STALE map entries: {len(stale)} -> {stale}")
    print(f"wrote {Path(args.out).relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
