"""Tool router — re-exports all per-asset tool modules."""
import json, sqlite3

from tools.github import sheet_agent, finance_records_agent, query_finance_expense_reports, lookup_finance_expense_report_with_employees, finance_workflow_agent, update_finance_expense_reports_status
from tools.notion import read_file, query_documents, operations_records_agent, document_agent, operations_workflow_agent, read_matter_document, draft_matter_document
from tools.calendar import list_scheduled_runs, query_calendar_events, calendar_agent, create_scheduled_run
from tools.core import query_files, list_playbooks, search_memory, search_knowledge, human_resources_records_agent, marketing_records_agent, get_business_units, list_business_units, list_quote, get_quote, get_activity, list_activity, list_invariants_verifiable, get_invariants_verifiable, get_sales_manager_policy, list_sales_manager_policy, query_departments, query_employees, query_employee_work_assignments, query_sales_opportunities, query_hr_leave_requests, query_hr_performance_reviews, query_finance_budgets, query_marketing_content_assets, query_sourcing_vendors, query_marketing_campaigns, lookup_employee_with_departments, lookup_employee_work_assignment_with_employees, lookup_hr_leave_request_with_employees, lookup_finance_budget_with_departments, lookup_marketing_campaign_with_employees, lookup_marketing_content_asset_with_marketing_campaigns, save_memory, add_to_knowledge, create_playbook, human_resources_workflow_agent, marketing_workflow_agent, create_business_units, update_status_business_units, create_quote, update_status_quote, create_activity, update_status_activity, create_invariants_verifiable, update_status_invariants_verifiable, create_sales_manager_policy, update_status_sales_manager_policy, update_departments_department_code, update_employees_status, update_employee_work_assignments_status, update_sales_opportunities_status, update_hr_leave_requests_status, update_hr_performance_reviews_status, update_finance_budgets_status, update_marketing_campaigns_status, update_marketing_content_assets_status, update_sourcing_vendors_status
from tools.jira import customer_support_records_agent, query_support_tickets, lookup_support_ticket_with_employees, customer_support_workflow_agent, update_support_tickets_status
from tools.email import organization_records_agent, organization_workflow_agent
from tools.salesforce import sales_records_agent, sourcing_records_agent, list_lead, get_account, list_account, list_opportunity, get_lead, get_opportunity, query_sales_leads, lookup_sales_lead_with_employees, core_workflow_agent, sales_workflow_agent, sourcing_workflow_agent, create_lead, update_status_lead, create_account, update_status_account, create_opportunity, update_status_opportunity, update_sales_leads_status
from tools.erp import query_sourcing_purchase_orders, lookup_sourcing_purchase_order_with_sourcing_vendors, update_sourcing_purchase_orders_status

TOOL_REGISTRY = {
    "sheet_agent": sheet_agent,
    "read_file": read_file,
    "list_scheduled_runs": list_scheduled_runs,
    "query_files": query_files,
    "list_playbooks": list_playbooks,
    "query_documents": query_documents,
    "query_calendar_events": query_calendar_events,
    "search_memory": search_memory,
    "search_knowledge": search_knowledge,
    "customer_support_records_agent": customer_support_records_agent,
    "finance_records_agent": finance_records_agent,
    "human_resources_records_agent": human_resources_records_agent,
    "organization_records_agent": organization_records_agent,
    "marketing_records_agent": marketing_records_agent,
    "sales_records_agent": sales_records_agent,
    "operations_records_agent": operations_records_agent,
    "sourcing_records_agent": sourcing_records_agent,
    "get_business_units": get_business_units,
    "list_business_units": list_business_units,
    "list_lead": list_lead,
    "get_account": get_account,
    "list_account": list_account,
    "list_opportunity": list_opportunity,
    "get_lead": get_lead,
    "list_quote": list_quote,
    "get_opportunity": get_opportunity,
    "get_quote": get_quote,
    "get_activity": get_activity,
    "list_activity": list_activity,
    "list_invariants_verifiable": list_invariants_verifiable,
    "get_invariants_verifiable": get_invariants_verifiable,
    "get_sales_manager_policy": get_sales_manager_policy,
    "list_sales_manager_policy": list_sales_manager_policy,
    "query_departments": query_departments,
    "query_employees": query_employees,
    "query_sales_leads": query_sales_leads,
    "query_employee_work_assignments": query_employee_work_assignments,
    "query_sales_opportunities": query_sales_opportunities,
    "query_hr_leave_requests": query_hr_leave_requests,
    "query_hr_performance_reviews": query_hr_performance_reviews,
    "query_finance_budgets": query_finance_budgets,
    "query_finance_expense_reports": query_finance_expense_reports,
    "query_support_tickets": query_support_tickets,
    "query_marketing_content_assets": query_marketing_content_assets,
    "query_sourcing_vendors": query_sourcing_vendors,
    "query_marketing_campaigns": query_marketing_campaigns,
    "query_sourcing_purchase_orders": query_sourcing_purchase_orders,
    "lookup_employee_with_departments": lookup_employee_with_departments,
    "lookup_employee_work_assignment_with_employees": lookup_employee_work_assignment_with_employees,
    "lookup_sales_lead_with_employees": lookup_sales_lead_with_employees,
    "lookup_hr_leave_request_with_employees": lookup_hr_leave_request_with_employees,
    "lookup_finance_expense_report_with_employees": lookup_finance_expense_report_with_employees,
    "lookup_finance_budget_with_departments": lookup_finance_budget_with_departments,
    "lookup_support_ticket_with_employees": lookup_support_ticket_with_employees,
    "lookup_marketing_campaign_with_employees": lookup_marketing_campaign_with_employees,
    "lookup_marketing_content_asset_with_marketing_campaigns": lookup_marketing_content_asset_with_marketing_campaigns,
    "lookup_sourcing_purchase_order_with_sourcing_vendors": lookup_sourcing_purchase_order_with_sourcing_vendors,
    "document_agent": document_agent,
    "calendar_agent": calendar_agent,
    "save_memory": save_memory,
    "add_to_knowledge": add_to_knowledge,
    "create_playbook": create_playbook,
    "create_scheduled_run": create_scheduled_run,
    "core_workflow_agent": core_workflow_agent,
    "customer_support_workflow_agent": customer_support_workflow_agent,
    "finance_workflow_agent": finance_workflow_agent,
    "human_resources_workflow_agent": human_resources_workflow_agent,
    "marketing_workflow_agent": marketing_workflow_agent,
    "operations_workflow_agent": operations_workflow_agent,
    "organization_workflow_agent": organization_workflow_agent,
    "sales_workflow_agent": sales_workflow_agent,
    "sourcing_workflow_agent": sourcing_workflow_agent,
    "create_business_units": create_business_units,
    "update_status_business_units": update_status_business_units,
    "create_lead": create_lead,
    "update_status_lead": update_status_lead,
    "create_account": create_account,
    "update_status_account": update_status_account,
    "create_opportunity": create_opportunity,
    "update_status_opportunity": update_status_opportunity,
    "create_quote": create_quote,
    "update_status_quote": update_status_quote,
    "create_activity": create_activity,
    "update_status_activity": update_status_activity,
    "create_invariants_verifiable": create_invariants_verifiable,
    "update_status_invariants_verifiable": update_status_invariants_verifiable,
    "create_sales_manager_policy": create_sales_manager_policy,
    "update_status_sales_manager_policy": update_status_sales_manager_policy,
    "update_departments_department_code": update_departments_department_code,
    "update_employees_status": update_employees_status,
    "update_employee_work_assignments_status": update_employee_work_assignments_status,
    "update_sales_leads_status": update_sales_leads_status,
    "update_sales_opportunities_status": update_sales_opportunities_status,
    "update_hr_leave_requests_status": update_hr_leave_requests_status,
    "update_hr_performance_reviews_status": update_hr_performance_reviews_status,
    "update_finance_expense_reports_status": update_finance_expense_reports_status,
    "update_finance_budgets_status": update_finance_budgets_status,
    "update_support_tickets_status": update_support_tickets_status,
    "update_marketing_campaigns_status": update_marketing_campaigns_status,
    "update_marketing_content_assets_status": update_marketing_content_assets_status,
    "update_sourcing_vendors_status": update_sourcing_vendors_status,
    "update_sourcing_purchase_orders_status": update_sourcing_purchase_orders_status,
    "read_matter_document": read_matter_document,
    "draft_matter_document": draft_matter_document,
}

