#!/usr/bin/env python3
"""Summarise the World Contribution Packages into docs/INGESTION-REPORT.md.

    python3 scripts/ingest/report.py

The report exists so coverage is a measurement rather than a judgement. Every
number here is counted from the WCPs; every refusal an adapter recorded is
carried through rather than rounded away.
"""
from __future__ import annotations

import collections
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WCP = ROOT / "research" / "parity" / "wcp"
OUT = ROOT / "docs" / "INGESTION-REPORT.md"


def main() -> int:
    pkgs = [json.loads(p.read_text()) for p in sorted(WCP.glob("*.json"))]
    if not pkgs:
        print("no WCPs; run scripts/ingest/ingest.py first")
        return 1

    by_adapter: dict[str, list[dict]] = collections.defaultdict(list)
    for p in pkgs:
        by_adapter[p["adapter"]["name"]].append(p)

    fidelity = collections.Counter()
    for p in pkgs:
        for t in p["tasks"]:
            fidelity[t.get("fidelity", p["fidelity"])] += 1
    verifiers = collections.Counter(
        t["verifier"]["kind"] for p in pkgs for t in p["tasks"] if t.get("verifier"))
    licenses = collections.Counter(p["source"]["license"] for p in pkgs)

    tot_tasks = sum(len(p["tasks"]) for p in pkgs)
    tot_tools = sum(len(p["tools"]) for p in pkgs)
    tot_tables = sum(len(p["tables"]) for p in pkgs)
    tot_rows = sum(t.get("row_count", 0) for p in pkgs for t in p["tables"])
    tot_refused = sum(r["count"] for p in pkgs for r in p["refusals"])

    L = [
        "# Ingestion report — what the corpus actually yields",
        "",
        "Generated by `scripts/ingest/report.py` from the World Contribution Packages",
        "in `research/parity/wcp/`. Process: [`docs/INGESTION-PROTOCOL.md`](INGESTION-PROTOCOL.md).",
        "",
        "Every figure below is counted, not estimated, and every refusal an adapter",
        "recorded is carried through. A task counted here is *ingested*, which is not",
        "the same as *running* — see the fidelity table and the pipeline status at the end.",
        "",
        "## Totals",
        "",
        f"- source packages: **{len(pkgs)}** from **{len({p['source']['repo'] for p in pkgs})}** repositories",
        f"- tasks / candidates ingested: **{tot_tasks:,}**",
        f"- tool declarations: **{tot_tools:,}**",
        f"- tables: **{tot_tables}** carrying **{tot_rows:,}** rows",
        f"- artifacts explicitly refused: **{tot_refused:,}**",
        "",
        "## Fidelity of ingested tasks",
        "",
        "| level | tasks | what it licenses us to claim |",
        "|---|---:|---|",
        f"| `exact` | {fidelity.get('exact', 0):,} | reproduces the source benchmark; comparable to its published numbers |",
        f"| `adapted` | {fidelity.get('adapted', 0):,} | same task and ground truth, our tool surface |",
        f"| `inspired` | {fidelity.get('inspired', 0):,} | grounded in the source; no ground truth carried over |",
        "",
        "## Verifier archetypes",
        "",
        "| archetype | tasks | how the world checks it |",
        "|---|---:|---|",
        f"| `answer_match` | {verifiers.get('answer_match', 0):,} | agent's answer vs ground truth (exact / fuzzy) |",
        f"| `action_trace` | {verifiers.get('action_trace', 0):,} | `/verifier/trace` — required tool calls |",
        f"| `state_assert` | {verifiers.get('state_assert', 0):,} | `/verifier/query`, incl. seed collateral diffs |",
        f"| `none` | {verifiers.get('none', 0):,} | workflow candidates; ground truth must be authored |",
        "",
        "## By adapter",
        "",
        "| adapter | pkgs | tasks | tools | tables | rows | refused |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for name, ps in sorted(by_adapter.items(), key=lambda kv: -sum(len(p["tasks"]) for p in kv[1])):
        L.append(f"| `{name}` | {len(ps)} | {sum(len(p['tasks']) for p in ps):,} | "
                 f"{sum(len(p['tools']) for p in ps):,} | {sum(len(p['tables']) for p in ps)} | "
                 f"{sum(t.get('row_count', 0) for p in ps for t in p['tables']):,} | "
                 f"{sum(r['count'] for p in ps for r in p['refusals']):,} |")

    L += ["", "## Largest tool contributions", "",
          "| vendor | verbs | source |", "|---|---:|---|"]
    tool_pkgs = sorted((p for p in pkgs if p["tools"]), key=lambda p: -len(p["tools"]))[:15]
    for p in tool_pkgs:
        ns = p["tools"][0]["namespace"]
        L.append(f"| `{ns}` | {len(p['tools'])} | `{p['source']['repo']}` |")

    L += ["", "## Licences of ingested sources", "",
          "Vendoring data or code requires a permissive licence; deriving *facts* does not.",
          "", "| licence | packages |", "|---|---:|"]
    for lic, n in licenses.most_common():
        L.append(f"| {lic} | {n} |")

    L += ["", "## Refusals — what could not be ported faithfully", "",
          "| kind | what | why | count |", "|---|---|---|---:|"]
    agg: dict[tuple, int] = collections.defaultdict(int)
    for p in pkgs:
        for r in p["refusals"]:
            agg[(r["kind"], r["what"], r["why"])] += r["count"]
    for (kind, what, why), n in sorted(agg.items(), key=lambda kv: -kv[1])[:14]:
        L.append(f"| {kind} | {what} | {why[:110]} | {n:,} |")

    L += [
        "",
        "## Pipeline status — ingested is not running",
        "",
        "| stage | state |",
        "|---|---|",
        f"| ingested into WCPs | **{tot_tasks:,} tasks** |",
        "| compiled to Harbor tasks | 16 (the hand-authored `sales-world` suite) |",
        "| passing the oracle gate | 16 / 16 |",
        "| measured against a model | 16 (grok-4.5, DeepSeek v4-flash) |",
        "",
        "The gap between the first and second rows is the honest statement of where",
        "this stands: the corpus is consumable and normalized, and the compiler that",
        "turns WCP tasks into Harbor tasks currently only covers the authored suite.",
        "Closing it is mechanical for `answer_match` (CRMArena) once the parity world",
        "serves the SOQL surface, and needs a state importer for `action_trace`",
        "(tau-bench seeds its DB through its own env).",
        "",
    ]
    OUT.write_text("\n".join(L))
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  {len(pkgs)} pkgs | {tot_tasks:,} tasks | {tot_tools:,} tools | "
          f"{tot_tables} tables / {tot_rows:,} rows | {tot_refused:,} refused")
    print(f"  fidelity: {dict(fidelity)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
